// 常见 MCP 的预设。fields 里的键会变成 env 或替换 args 里的 {{占位}}。
export const PRESETS = [
  { id: "feishu", name: "飞书 / Lark", desc: "官方 lark-mcp：读写文档、日历、消息。需要在飞书开放平台建一个自建应用。",
    type: "stdio", command: "npx", args: ["-y", "@larksuiteoapi/lark-mcp", "mcp", "-a", "{{APP_ID}}", "-s", "{{APP_SECRET}}"],
    fields: [{ key: "APP_ID", label: "App ID", secret: false }, { key: "APP_SECRET", label: "App Secret", secret: true }],
    help: "https://github.com/larksuite/lark-openapi-mcp" },
  { id: "slack", name: "Slack", desc: "读频道、搜消息、发消息。需要一个 Slack App 的 Bot Token（xoxb-）。",
    type: "stdio", command: "npx", args: ["-y", "@ubie-oss/slack-mcp-server"],
    fields: [{ key: "SLACK_BOT_TOKEN", label: "Bot Token (xoxb-…)", secret: true }, { key: "SLACK_USER_TOKEN", label: "User Token (xoxp-…，搜索要用，可选)", secret: true }],
    help: "https://github.com/ubie-oss/slack-mcp-server" },
  { id: "notion", name: "Notion", desc: "读写 Notion 页面和数据库。需要 Integration Token。",
    type: "stdio", command: "npx", args: ["-y", "@notionhq/notion-mcp-server"],
    fields: [{ key: "NOTION_TOKEN", label: "Integration Token (ntn_…)", secret: true }],
    help: "https://github.com/makenotion/notion-mcp-server" },
  { id: "github", name: "GitHub", desc: "看 issue、PR、仓库。需要一个 Personal Access Token。",
    type: "http", url: "https://api.githubcopilot.com/mcp/", headers: { Authorization: "Bearer {{GITHUB_TOKEN}}" },
    fields: [{ key: "GITHUB_TOKEN", label: "Personal Access Token", secret: true }],
    help: "https://github.com/github/github-mcp-server" },
  { id: "spotify", name: "Spotify", desc: "控制播放、搜歌、管播放列表。需要在 Spotify 开发者后台建应用。",
    type: "stdio", command: "npx", args: ["-y", "spotify-mcp-server"],
    fields: [{ key: "SPOTIFY_CLIENT_ID", label: "Client ID", secret: false }, { key: "SPOTIFY_CLIENT_SECRET", label: "Client Secret", secret: true }],
    help: "https://github.com/marcelmarais/spotify-mcp-server" },
  { id: "google", name: "Google 日历 + Gmail", desc: "看日程、读邮件（只读）。需要 Google Cloud 的 OAuth 客户端。",
    type: "stdio", command: "{{UVX}}", args: ["--python", "{{PYTHON}}", "workspace-mcp", "--single-user", "--tools", "gmail", "calendar", "--tool-tier", "core", "--read-only"],
    fields: [{ key: "GOOGLE_OAUTH_CLIENT_ID", label: "OAuth Client ID", secret: false }, { key: "GOOGLE_OAUTH_CLIENT_SECRET", label: "OAuth Client Secret", secret: true }, { key: "USER_GOOGLE_EMAIL", label: "你的 Gmail（可选）", secret: false }],
    extraEnv: { OAUTHLIB_INSECURE_TRANSPORT: "1" },
    help: "https://github.com/taylorwilsdon/google_workspace_mcp" },
  { id: "netease", name: "网易云音乐", desc: "本机装了网易云客户端才行。先跑 scripts/setup-netease.sh。",
    type: "stdio", command: "{{NETEASE_BIN}}", args: [],
    fields: [{ key: "NETEASE_BIN", label: "cloud-music-mcp 可执行文件路径", secret: false, arg: true }],
    help: "https://github.com/Code-MonkeyZhang/cloud-music-mcp" },
  { id: "filesystem", name: "文件夹", desc: "让它能读某个文件夹里的文件。",
    type: "stdio", command: "npx", args: ["-y", "@modelcontextprotocol/server-filesystem", "{{DIR}}"],
    fields: [{ key: "DIR", label: "文件夹路径", secret: false, arg: true }],
    help: "https://github.com/modelcontextprotocol/servers" },
  { id: "custom", name: "自定义", desc: "任何 MCP：本地命令（stdio）或网址（http / sse）。", type: "stdio", command: "", args: [], fields: [] }
];
