// 英雄皮肤：致敬漫威的原创 Q 版设计（自己画的，不是漫威素材），每位有自己的特效、台词和音色。
// 反应表的写法和 live2dCatalog.js 一样：fx / hop / spin / squash / delay，外加 pose（英雄各自的姿势，见 heroes.js）。
export const HEROES = {
  hero_iron: {
    kind: "iron", name: "钢铁侠", full: "钢铁侠风 · 铁甲", gender: "男", desc: "英雄 · 红金战甲、胸口方舟反应堆 · 冲击波与推进器特效", hit: [1.15, 1.7, -0.25],
    theme: { colors: ["#9FE9FF", "#FFFFFF", "#F2B134"] },
    react: {
      pet: [{ pose: ["glow", 1500], fx: [["burst", "sparkle", 3, { at: "chest", colors: ["#9FE9FF", "#FFFFFF"], speed: 40 }]] }],
      poke: [{ pose: ["repulsor", 900], fx: [["glow", { color: "#9FE9FF", at: "chest", dur: 0.9 }], ["burst", "spark", 8, { at: "handR", speed: 140, colors: ["#9FE9FF", "#FFFFFF"] }]] }],
      "rps:reveal": [{ pose: ["point", 900], fx: [["hud", { color: "#9FE9FF", r: 44, dur: 1.2 }]] }],
      "rps:win": [{ pose: ["repulsor", 1400], fx: [["flash", { color: "#BFEFFF", alpha: 0.45 }], ["lines", { color: "#5FC9F5", n: 18, len: 60 }], ["ring", { color: "#9FE9FF", r1: 100 }], ["burst", "spark", 18, { at: "handR", speed: 220, colors: ["#9FE9FF", "#FFFFFF"] }]] }],
      "rps:lose": [{ pose: ["sag", 2200], fx: [["burst", "spark", 10, { at: "chest", speed: 120, colors: ["#FF9F43", "#FFD27F"] }], ["rise", "smoke", 8, { at: "chest", speed: 0.7 }]] }],
      "rps:tie": [{ pose: ["point", 1200], fx: [["hud", { color: "#F2B134", r: 44, dur: 1.4 }], ["text", "?", { color: "#F2B134", size: 24, at: "headR" }]] }],
      "dice:start": [{ pose: ["point", 800], hop: 1, fx: [["rise", "ember", 10, { at: "feet", speed: 1.4 }]] }],
      "dice:win": [{ hop: 1, pose: ["fly", 1200], fx: [["rise", "ember", 24, { at: "feet", speed: 1.8, stagger: 0.03 }], ["ring", { color: "#FF9F43", r1: 90 }], ["burst", "sparkle", 8, { at: "chest", colors: ["#9FE9FF", "#FFFFFF"] }]] }],
      "dice:lose": [{ pose: ["sag", 2000], fx: [["rise", "smoke", 8, { at: "chest" }], ["cloud", { dur: 1.8 }]] }],
      "dice:tie": [{ fx: [["hud", { color: "#F2B134", r: 44 }]] }],
      "catch:start": [{ pose: ["point", 900], fx: [["hud", { color: "#9FE9FF", r: 40, dur: 1 }]] }],
      "catch:get": [{ fx: [["burst", "spark", 2, { speed: 60, size: 0.8, colors: ["#9FE9FF"] }]] }],
      "catch:five": [{ pose: ["glow", 900], fx: [["ring", { color: "#9FE9FF", r1: 70, dur: 0.5, at: "chest" }]] }],
      "catch:miss": [{ fx: [["burst", "spark", 2, { at: "chest", speed: 60, colors: ["#FF9F43"] }]] }],
      "catch:great": [{ pose: ["repulsor", 1600], fx: [["flash", { color: "#BFEFFF", alpha: 0.4 }], ["hud", { color: "#9FE9FF", r: 60, dur: 2 }], ["burst", "spark", 22, { at: "handR", speed: 220, colors: ["#9FE9FF", "#FFFFFF"] }], ["ring", { color: "#9FE9FF", r1: 100 }]] }],
      "catch:ok": [{ pose: ["glow", 1500], fx: [["burst", "sparkle", 6, { at: "chest", colors: ["#9FE9FF"] }]] }],
      "catch:bad": [{ pose: ["sag", 2200], fx: [["rise", "smoke", 8, { at: "chest" }], ["cloud", { dur: 2 }]] }],
      land: [{ fx: [["ring", { color: "#FF9F43", r1: 70, dur: 0.5 }], ["rise", "ember", 6, { at: "feet" }]] }],
      spin: [{ fx: [["hud", { color: "#9FE9FF", r: 50, dur: 1 }]] }],
      throw: [{ fx: [["rise", "ember", 12, { at: "feet", speed: 1.6 }]] }]
    },
    voice: { id: "Chinese (Mandarin)_Unrestrained_Young_Man", speed: 1.02, pitch: 0 },
    greeting: "系统上线。我是钢铁侠……好吧，桌面版的。",
    style: "自信、爱调侃、满嘴科技名词，偶尔自恋，但关键时刻靠得住。",
    lines: { rps: { win: "我出{it}。算法早就算到了。", lose: "{it}……这局不算，我的传感器被干扰了。", tie: "都出{it}？你抄我作业。" }, dice: { win: "{it} 点对 {me} 点，物理学站在我这边。", lose: "{it} 点……我得升级一下运气模块。", tie: "都是 {it} 点，概率学的小玩笑。" }, catch: { great: "{n} 个。反应速度可以，考虑给你做套装甲。", ok: "{n} 个，中规中矩。", bad: "{n} 个……要不我给你装个自动瞄准？" } }
  },
  hero_spider: {
    kind: "spider", name: "蜘蛛侠", full: "蜘蛛侠风 · 蛛网", gender: "男", desc: "英雄 · 红蓝紧身衣、大白眼罩 · 蛛丝与倒挂特效", hit: [1.1, 1.7, -0.25],
    theme: { colors: ["#F4F4F4", "#D32F2F", "#1E4DB7"] },
    react: {
      pet: [{ pose: ["happy", 1500], fx: [["burst", "heart", 2, { at: "headR", speed: 40 }]] }],
      poke: [{ pose: ["shoot", 1000], fx: [["web", { at: "handR", tx: 280, ty: 20 }], ["text", "嗖", { color: "#33303A", size: 16, at: "headR" }]] }],
      "rps:reveal": [{ pose: ["crouch", 900] }],
      "rps:win": [{ pose: ["flip", 700], fx: [["web", { at: "handR", tx: 290, ty: 30 }], ["web", { at: "handL", tx: 10, ty: 40 }], ["burst", "confetti", 24, { speed: 160, lift: 120, colors: ["#D32F2F", "#1E4DB7", "#FFFFFF"] }]] }],
      "rps:lose": [{ pose: ["hang", 2600], fx: [["burst", "sweat", 1, { at: "headR", speed: 20, lift: 0 }]] }],
      "rps:tie": [{ pose: ["shrug", 1400], fx: [["text", "?", { size: 24, at: "headR" }]] }],
      "dice:start": [{ pose: ["crouch", 900], hop: 1 }],
      "dice:win": [{ pose: ["flip", 700], fx: [["web", { at: "handR", tx: 290, ty: 30 }], ["burst", "sparkle", 8, { colors: ["#FFFFFF", "#D32F2F"] }]] }],
      "dice:lose": [{ pose: ["hang", 2400], fx: [["cloud", { dur: 1.8 }]] }],
      "dice:tie": [{ pose: ["shrug", 1200] }],
      "catch:start": [{ pose: ["crouch", 900] }],
      "catch:get": [{ fx: [["burst", "sparkle", 2, { speed: 50, size: 0.7, colors: ["#F4F4F4"] }]] }],
      "catch:five": [{ pose: ["shoot", 800], fx: [["web", { at: "handR", tx: 285, ty: 25 }]] }],
      "catch:miss": [{ pose: ["crouch", 500] }],
      "catch:great": [{ pose: ["flip", 700], fx: [["web", { at: "handR", tx: 290, ty: 30 }], ["web", { at: "handL", tx: 10, ty: 40 }], ["shower", "confetti", 40, { dur: 1.6, colors: ["#D32F2F", "#1E4DB7", "#FFFFFF"] }]] }],
      "catch:ok": [{ pose: ["happy", 1500], fx: [["burst", "sparkle", 6, { colors: ["#F4F4F4"] }]] }],
      "catch:bad": [{ pose: ["hang", 2400], fx: [["cloud", { dur: 2 }]] }],
      land: [{ pose: ["crouch", 500], fx: [["ring", { color: "#D32F2F", r1: 60, dur: 0.45 }]] }],
      spin: [{ pose: ["flip", 700] }],
      throw: [{ fx: [["web", { at: "handR", tx: 290, ty: 10 }]] }]
    },
    voice: { id: "Chinese (Mandarin)_Straightforward_Boy", speed: 1.08, pitch: 0 },
    greeting: "嘿！你友好的邻居蜘蛛侠，报到！",
    style: "话痨、爱开玩笑、热情的邻家男孩，句子里常带「嘿」「哇」，紧张的时候更话痨。",
    lines: { rps: { win: "我出{it}！蜘蛛感应没骗我！", lose: "{it}……好吧好吧，这局你赢，别告诉别人。", tie: "都是{it}！咱俩心灵感应？" }, dice: { win: "{it} 点！哇，我今天手气爆棚！", lose: "{it} 点……这骰子肯定是反派派来的。", tie: "都是 {it} 点，平局也挺酷的。" }, catch: { great: "{n} 个！你比我的蛛丝还准！", ok: "{n} 个，不错嘛！", bad: "{n} 个……没事，下次我吐点蛛丝帮你兜着。" } }
  },
  hero_hulk: {
    kind: "hulk", name: "绿巨人", full: "绿巨人风 · 浩克", gender: "男", desc: "英雄 · 绿皮大块头、紫裤子 · 砸地冲击波与震屏特效", hit: [1.5, 1.6, -0.15],
    theme: { colors: ["#7FC8A9", "#4CAF50"] },
    react: {
      pet: [{ pose: ["calm", 1800], fx: [["burst", "heart", 2, { at: "headR", speed: 40 }]] }],
      poke: [{ pose: ["flex", 1000], fx: [["text", "吼！", { color: "#2E7D32", size: 20, at: "headR" }], ["burst", "dot", 6, { at: "feet", speed: 80, colors: ["#C9B99A"] }]] }],
      "rps:reveal": [{ pose: ["flex", 900] }],
      "rps:win": [{ pose: ["smash", 900] }, { delay: 420, fx: [["shake", { amp: 7, dur: 0.5 }], ["ring", { color: "#8D6E63", r1: 120, width: 5 }], ["lines", { color: "#5D4037", n: 16, len: 50, at: "feet" }], ["burst", "dot", 16, { at: "feet", speed: 160, colors: ["#C9B99A", "#8D6E63"] }], ["text", "砸！", { color: "#2E7D32", size: 24, at: "headR" }]] }],
      "rps:lose": [{ pose: ["sulk", 2400], fx: [["rise", "smoke", 6, { at: "head", speed: 0.7 }], ["cloud", { dur: 2 }]] }],
      "rps:tie": [{ pose: ["shrug", 1300], fx: [["text", "?", { size: 26, at: "headR", color: "#2E7D32" }]] }],
      "dice:start": [{ pose: ["flex", 900], hop: 1 }],
      "dice:win": [{ pose: ["smash", 900] }, { delay: 420, fx: [["shake", { amp: 6 }], ["ring", { color: "#8D6E63", r1: 110, width: 5 }], ["burst", "dot", 14, { at: "feet", speed: 150, colors: ["#C9B99A", "#8D6E63"] }]] }],
      "dice:lose": [{ pose: ["sulk", 2200], fx: [["cloud", { dur: 1.8 }]] }],
      "dice:tie": [{ pose: ["shrug", 1200] }],
      "catch:start": [{ pose: ["flex", 900] }],
      "catch:get": [{ fx: [["burst", "dot", 2, { speed: 50, size: 0.8, colors: ["#7FC8A9"] }]] }],
      "catch:five": [{ pose: ["flex", 800], fx: [["shake", { amp: 3, dur: 0.3 }]] }],
      "catch:miss": [{ pose: ["sulk", 500] }],
      "catch:great": [{ pose: ["smash", 900] }, { delay: 420, fx: [["shake", { amp: 8, dur: 0.6 }], ["ring", { color: "#8D6E63", r1: 130, width: 6 }], ["lines", { color: "#5D4037", n: 18, len: 56, at: "feet" }], ["burst", "dot", 20, { at: "feet", speed: 170, colors: ["#C9B99A", "#8D6E63"] }], ["text", "砸！", { color: "#2E7D32", size: 26, at: "headR" }]] }],
      "catch:ok": [{ pose: ["flex", 1200] }],
      "catch:bad": [{ pose: ["sulk", 2400], fx: [["cloud", { dur: 2 }]] }],
      land: [{ fx: [["shake", { amp: 5, dur: 0.4 }], ["ring", { color: "#8D6E63", r1: 100, width: 5, dur: 0.6 }], ["burst", "dot", 10, { at: "feet", speed: 120, colors: ["#C9B99A"] }]] }],
      spin: [{ pose: ["flex", 800] }],
      throw: [{ pose: ["flex", 600] }]
    },
    voice: { id: "Chinese (Mandarin)_Male_Announcer", speed: 0.9, pitch: -6 },
    greeting: "绿巨人……来了。",
    style: "话很少，句子短、大声，喜欢用「砸」，用第三人称叫自己「绿巨人」，被摸的时候会难得温柔一下。",
    lines: { rps: { win: "{it}！绿巨人赢！", lose: "{it}……绿巨人……不开心。", tie: "都是{it}。哼。" }, dice: { win: "{it} 点！砸！", lose: "{it} 点……骰子坏了。", tie: "一样。{it} 点。" }, catch: { great: "{n} 个！厉害！", ok: "{n} 个。还行。", bad: "{n} 个……再来！" } }
  },
  hero_loki: {
    kind: "loki", name: "洛基", full: "洛基风 · 诡计之神", gender: "男", desc: "英雄 · 金角盔、绿披风、权杖 · 幻影分身与绿焰特效", hit: [1.15, 1.75, -0.3],
    theme: { colors: ["#7CF5A8", "#3DDC84", "#D4AF37"] },
    react: {
      pet: [{ pose: ["smirk", 1500], fx: [["burst", "wisp", 3, { at: "headR", speed: 30, lift: 20 }]] }],
      poke: [{ pose: ["cast", 1100], fx: [["burst", "wisp", 8, { at: "handR", speed: 60, lift: 40 }], ["glow", { color: "#7CF5A8", at: "handR", r: 40, dur: 1 }]] }],
      "rps:reveal": [{ pose: ["cast", 900], fx: [["burst", "wisp", 4, { at: "handR", speed: 40 }]] }],
      "rps:win": [{ pose: ["clones", 1600], fx: [["magic", { color: "#3DDC84", dur: 1.8, r: 80 }], ["burst", "wisp", 16, { speed: 110, lift: 60 }], ["burst", "sparkle", 6, { colors: ["#D4AF37", "#FFFFFF"] }]] }],
      "rps:lose": [{ pose: ["vanish", 1400], fx: [["rise", "smoke", 10, { at: "chest", colors: ["#3DDC84", "#7CF5A8"], speed: 1.2 }]] }, { delay: 1400, pose: ["smirk", 1200], fx: [["burst", "wisp", 4]] }],
      "rps:tie": [{ pose: ["bow", 1300], fx: [["burst", "wisp", 5, { speed: 40 }]] }],
      "dice:start": [{ pose: ["cast", 900], fx: [["burst", "wisp", 5, { at: "handR" }]] }],
      "dice:win": [{ pose: ["clones", 1500], fx: [["burst", "wisp", 14, { speed: 100 }], ["magic", { color: "#3DDC84", r: 70 }]] }],
      "dice:lose": [{ pose: ["vanish", 1400], fx: [["rise", "smoke", 10, { at: "chest", colors: ["#3DDC84"] }]] }, { delay: 1400, pose: ["smirk", 1000] }],
      "dice:tie": [{ pose: ["bow", 1200] }],
      "catch:start": [{ pose: ["cast", 900] }],
      "catch:get": [{ fx: [["burst", "wisp", 1, { speed: 40, size: 0.8 }]] }],
      "catch:five": [{ pose: ["cast", 800], fx: [["burst", "wisp", 6, { at: "handR" }]] }],
      "catch:miss": [{ pose: ["smirk", 500] }],
      "catch:great": [{ pose: ["clones", 1800], fx: [["magic", { color: "#3DDC84", dur: 2, r: 90 }], ["shower", "wisp", 26, { dur: 1.6 }], ["burst", "sparkle", 8, { colors: ["#D4AF37"] }]] }],
      "catch:ok": [{ pose: ["smirk", 1500], fx: [["burst", "wisp", 6]] }],
      "catch:bad": [{ pose: ["vanish", 1400], fx: [["rise", "smoke", 8, { at: "chest", colors: ["#3DDC84"] }], ["cloud", { dur: 2 }]] }, { delay: 1400, pose: ["smirk", 800] }],
      land: [{ fx: [["magic", { color: "#3DDC84", dur: 0.8, r: 55 }]] }],
      spin: [{ pose: ["clones", 900] }],
      throw: [{ fx: [["burst", "wisp", 8, { speed: 80 }]] }]
    },
    voice: { id: "lengdan_xiongzhang", speed: 0.97, pitch: -1 },
    greeting: "我是洛基，恶作剧之神。你的桌面归我了。",
    style: "傲慢优雅、狡黠，说话带点戏剧腔，自称神，输了也要嘴硬。",
    lines: { rps: { win: "{it}。在神面前，你还嫩了点。", lose: "{it}……那是我的分身，本尊没输。", tie: "都是{it}？你偷学了我的幻术。" }, dice: { win: "{it} 点，命运站在神这边。", lose: "{it} 点……骰子被人动了手脚，一定是。", tie: "都是 {it} 点，无趣。" }, catch: { great: "{n} 个。勉强够资格当我的手下。", ok: "{n} 个，尚可。", bad: "{n} 个……凡人的手，也就这样了。" } }
  },
  hero_thor: {
    kind: "thor", name: "雷神", full: "雷神风 · 托尔", gender: "男", desc: "英雄 · 红披风、银翼盔、大锤 · 天降闪电特效", hit: [1.2, 1.75, -0.3],
    theme: { colors: ["#FFF7B0", "#7FD0FF", "#FFFFFF"] },
    react: {
      pet: [{ pose: ["smile", 1500], fx: [["burst", "sparkle", 3, { at: "headR", speed: 40, colors: ["#FFF7B0"] }]] }],
      poke: [{ pose: ["swing", 900], fx: [["burst", "spark", 8, { at: "handR", speed: 120, colors: ["#FFF7B0", "#7FD0FF"] }]] }],
      "rps:reveal": [{ pose: ["guard", 900] }],
      "rps:win": [{ pose: ["raise", 1500], fx: [["bolt", { at: "handR", dur: 0.45 }], ["flash", { color: "#FFF7B0", alpha: 0.5 }], ["ring", { color: "#7FD0FF", r1: 100 }], ["lines", { color: "#7FD0FF", n: 16, len: 56 }], ["burst", "spark", 18, { at: "handR", speed: 200, colors: ["#FFF7B0", "#7FD0FF", "#FFFFFF"] }]] }, { delay: 500, fx: [["bolt", { at: "handR", dur: 0.35 }]] }],
      "rps:lose": [{ pose: ["storm", 2400], fx: [["cloud", { dur: 2.4, color: "#6E7C8A" }], ["burst", "sweat", 1, { at: "headR", speed: 20, lift: 0 }]] }],
      "rps:tie": [{ pose: ["guard", 1200], fx: [["burst", "spark", 5, { at: "handR", speed: 80, colors: ["#FFF7B0"] }], ["text", "?", { size: 24, at: "headR" }]] }],
      "dice:start": [{ pose: ["swing", 900] }],
      "dice:win": [{ pose: ["raise", 1400], fx: [["bolt", { at: "handR" }], ["flash", { color: "#FFF7B0", alpha: 0.4 }], ["burst", "spark", 14, { at: "handR", speed: 180, colors: ["#FFF7B0", "#7FD0FF"] }]] }],
      "dice:lose": [{ pose: ["storm", 2200], fx: [["cloud", { dur: 2.2, color: "#6E7C8A" }]] }],
      "dice:tie": [{ pose: ["guard", 1200] }],
      "catch:start": [{ pose: ["guard", 900] }],
      "catch:get": [{ fx: [["burst", "spark", 2, { speed: 60, size: 0.8, colors: ["#FFF7B0"] }]] }],
      "catch:five": [{ pose: ["swing", 800], fx: [["burst", "spark", 6, { at: "handR", colors: ["#FFF7B0", "#7FD0FF"] }]] }],
      "catch:miss": [{ pose: ["storm", 500] }],
      "catch:great": [{ pose: ["raise", 1800], fx: [["bolt", { at: "handR", dur: 0.5 }], ["flash", { color: "#FFF7B0", alpha: 0.5 }], ["ring", { color: "#7FD0FF", r1: 110 }], ["burst", "spark", 22, { at: "handR", speed: 220, colors: ["#FFF7B0", "#7FD0FF", "#FFFFFF"] }]] }, { delay: 450, fx: [["bolt", { at: "handR", dur: 0.35 }]] }, { delay: 900, fx: [["bolt", { at: "handR", dur: 0.35 }]] }],
      "catch:ok": [{ pose: ["smile", 1500], fx: [["burst", "spark", 6, { at: "handR", colors: ["#FFF7B0"] }]] }],
      "catch:bad": [{ pose: ["storm", 2400], fx: [["cloud", { dur: 2.4, color: "#6E7C8A" }]] }],
      land: [{ fx: [["ring", { color: "#7FD0FF", r1: 80, dur: 0.5 }], ["burst", "spark", 6, { at: "feet", speed: 90, colors: ["#FFF7B0"] }]] }],
      spin: [{ pose: ["swing", 900] }],
      throw: [{ pose: ["swing", 600] }]
    },
    voice: { id: "male-qn-badao-jingpin", speed: 0.96, pitch: -2 },
    greeting: "阿斯加德的托尔，在此！",
    style: "豪爽、大嗓门、有点古风腔，喜欢叫主人「朋友」，输了也大方。",
    lines: { rps: { win: "{it}！这一局，雷神胜！", lose: "{it}……好样的，朋友，你赢了。", tie: "都是{it}，势均力敌！" }, dice: { win: "{it} 点！雷电与我同在！", lose: "{it} 点……骰子不听雷神的话。", tie: "都是 {it} 点，痛快！" }, catch: { great: "{n} 个！好身手，朋友！", ok: "{n} 个，不赖。", bad: "{n} 个……再战一局！" } }
  },
  hero_jarvis: {
    kind: "jarvis", name: "贾维斯", full: "贾维斯风 · 全息管家", gender: "AI", desc: "AI 管家 · 悬浮的全息核心与旋转光环 · 说话时有声波，算概率时转得飞快", hit: [1.25, 1.25, -0.5], rK: 0.2, baseYK: 0.55,
    theme: { colors: ["#4FC3F7", "#FFFFFF", "#00BCD4"] },
    react: {
      pet: [{ pose: ["bright", 1500], fx: [["burst", "sparkle", 4, { at: "head", speed: 40, colors: ["#4FC3F7", "#FFFFFF"] }]] }],
      poke: [{ pose: ["compute", 1200], fx: [["hud", { color: "#4FC3F7", r: 62, dur: 1.4, at: "head" }]] }],
      "rps:reveal": [{ pose: ["compute", 1400], fx: [["hud", { color: "#4FC3F7", r: 58, dur: 1.4, at: "head" }]] }],
      "rps:win": [{ pose: ["expand", 1400], fx: [["ring", { color: "#4FC3F7", r1: 110, at: "head", dur: 0.9 }], ["burst", "sparkle", 14, { at: "head", speed: 120, colors: ["#4FC3F7", "#FFFFFF"] }], ["text", "100%", { color: "#4FC3F7", size: 18, at: "headR" }]] }],
      "rps:lose": [{ pose: ["alert", 2000], fx: [["text", "ERR", { color: "#FF6B6B", size: 16, at: "headR" }], ["burst", "spark", 6, { at: "head", speed: 80, colors: ["#FF6B6B"] }]] }],
      "rps:tie": [{ pose: ["scan", 1400], fx: [["text", "33%", { color: "#F2C46B", size: 16, at: "headR" }]] }],
      "dice:start": [{ pose: ["compute", 1200] }],
      "dice:win": [{ pose: ["expand", 1400], fx: [["ring", { color: "#4FC3F7", r1: 100, at: "head" }], ["hud", { color: "#4FC3F7", r: 60, at: "head", dur: 1.6 }], ["burst", "sparkle", 10, { at: "head", colors: ["#4FC3F7", "#FFFFFF"] }]] }],
      "dice:lose": [{ pose: ["alert", 1800], fx: [["text", "已记录", { color: "#FF6B6B", size: 14, at: "headR" }]] }],
      "dice:tie": [{ pose: ["scan", 1200] }],
      "catch:start": [{ pose: ["compute", 1200], fx: [["hud", { color: "#4FC3F7", r: 56, at: "head", dur: 1.2 }]] }],
      "catch:get": [{ fx: [["burst", "sparkle", 1, { speed: 40, size: 0.8, colors: ["#4FC3F7"] }]] }],
      "catch:five": [{ pose: ["bright", 800], fx: [["hud", { color: "#4FC3F7", r: 50, at: "head", dur: 0.9 }]] }],
      "catch:miss": [{ pose: ["alert", 500] }],
      "catch:great": [{ pose: ["expand", 1800], fx: [["ring", { color: "#4FC3F7", r1: 120, at: "head" }], ["shower", "sparkle", 26, { dur: 1.6, colors: ["#4FC3F7", "#FFFFFF"] }], ["text", "优秀", { color: "#4FC3F7", size: 18, at: "headR" }]] }],
      "catch:ok": [{ pose: ["bright", 1500], fx: [["burst", "sparkle", 6, { at: "head", colors: ["#4FC3F7"] }]] }],
      "catch:bad": [{ pose: ["alert", 2000], fx: [["text", "建议休息", { color: "#FF6B6B", size: 14, at: "headR" }]] }],
      land: [{ fx: [["ring", { color: "#4FC3F7", r1: 70, dur: 0.5 }]] }],
      spin: [{ pose: ["whirl", 900] }],
      throw: [{ pose: ["alert", 800] }]
    },
    voice: { id: "Chinese (Mandarin)_Reliable_Executive", speed: 1.0, pitch: 0 },
    greeting: "先生，系统已上线。有什么可以为您效劳？",
    style: "冷静、精准、有礼的管家式 AI，称呼主人「先生」，习惯报数据和概率，偶尔有一点英式冷幽默。",
    lines: { rps: { win: "我出{it}。胜率计算无误。", lose: "{it}……先生，您的随机性超出了模型预期。", tie: "都是{it}。概率百分之三十三，正常。" }, dice: { win: "{it} 点对 {me} 点，在预期范围内。", lose: "{it} 点，您的 {me} 点更大。已记录。", tie: "都是 {it} 点，先生。" }, catch: { great: "{n} 个。反应速度优秀，已存档。", ok: "{n} 个。表现稳定。", bad: "{n} 个。建议休息一下再试，先生。" } }
  }
};
